name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually via the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Sync with Upstream
        run: gh repo sync ${{ github.repository }} --source x1xhlol/system-prompts-and-models-of-ai-tools -b main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
